# Watcher Configuration Template
# This file contains configuration for a watcher instance

# Basic settings
name: "default"
watch_directory: "~/repo"
repo_directory: "~/repo"

# Timing settings (in seconds)
commit_delay: 60        # Wait time before committing after last change
fetch_interval: 600     # Interval between remote fetches (10 minutes)

# Notification settings
enable_notifications: true
notify_on_commit: true       # Send notification for main repo commits
notify_on_remote_changes: true

# Git settings
auto_push: true         # Automatically push after commits
respect_gitignore: true # Follow gitignore patterns

# Git operation controls
enable_commits: true    # Enable/disable automatic commits
enable_fetch: true      # Enable/disable periodic fetch operations
fetch_branches: []      # List of branches to fetch from (empty = all branches)

# Project-specific ignore patterns (in addition to global ignore file)
# Optional: Add patterns specific to this project
ignore_patterns: []
#  - "*.log"
#  - "build/"
#  - "dist/"

# Optional: Additional ignore files to read
# These files will be read in addition to the global ignore file
ignore_files: []
#  - "~/.config/watcher/nodejs-ignore"  # Language-specific ignore
#  - ".watcher-ignore"                  # Project-local ignore file
